      - name: Test with coverage (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        shell: bash
        run: |
          set -e
          go test ./... -coverprofile=coverage.out -count=1 -failfast -v 2>&1 | tee test.log

      - name: Test with coverage (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          go test ./... -coverprofile=coverage.out -count=1 -failfast -v *>&1 | Tee-Object -FilePath test.log

      - name: Coverage (functions)
        if: always()        # 失敗しても見たいので
        run: go tool cover -func=coverage.out || true

      - name: Coverage HTML
        if: always()
        run: go tool cover -html=coverage.out -o coverage.html || true

      - name: Upload test logs & coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ runner.os }}
          path: |
            test.log
            coverage.out
            coverage.html
