name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    name: Go Test & Coverage
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        go: [ '1.22.x' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Cache Go build
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ matrix.go }}-${{ hashFiles('**/go.mod', '**/go.sum') }}  
        restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go }}-

      - name: Go Vet
        run: go vet ./...

      - name: Build
        run: go build -o syncdir.exe

      - name: Test with coverage
        run: go test ./... -coverprofile=coverage.out -count=1 -failfast -v
      - name: Coverage (functions)
        run: go tool cover -func=coverage.out

      - name: Coverage HTML
        run: go tool cover -html=coverage.out -o coverage.html

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ runner.os }}
          path: |
            coverage.out
            coverage.html
